import com.sun.jdi.*;
import com.sun.jdi.connect.*;

import java.io.*;
import java.net.ConnectException;
import java.nio.file.*;
import java.util.*;

/**
 * JDWP HotSwap utility — connects to a running JVM debug port and redefines
 * changed .class files, exactly like IntelliJ's "Update classes and resources".
 *
 * Usage: java HotSwap <port> <classesDir> [sinceMillis] [-v]
 *   port        - JDWP debug port (e.g. 9009)
 *   classesDir  - directory containing compiled .class files (e.g. target/classes)
 *   sinceMillis - only swap classes modified after this epoch millis (optional, 0 = all)
 *   -v          - verbose: print each class name being swapped
 */
public class HotSwap {

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("Usage: java HotSwap <port> <classesDir> [sinceMillis]");
            System.exit(1);
        }

        String port = args[0];
        Path classesDir = Path.of(args[1]);
        long sinceMillis = args.length > 2 ? Long.parseLong(args[2]) : 0;
        boolean verbose = Arrays.asList(args).contains("-v");

        if (!Files.isDirectory(classesDir)) {
            System.err.println("Classes directory not found: " + classesDir);
            System.exit(1);
        }

        // Find all .class files (optionally filtered by modification time)
        List<Path> classFiles = new ArrayList<>();
        try (var walk = Files.walk(classesDir)) {
            walk.filter(p -> p.toString().endsWith(".class"))
                .filter(p -> {
                    if (sinceMillis <= 0) return true;
                    try {
                        return Files.getLastModifiedTime(p).toMillis() >= sinceMillis;
                    } catch (IOException e) {
                        return false;
                    }
                })
                .forEach(classFiles::add);
        }

        if (classFiles.isEmpty()) {
            System.out.println("No .class files found to swap.");
            System.exit(0);
        }

        // Connect to JVM via JDWP
        VirtualMachine vm = attach(port);
        try {
            // Diagnostic: check JVM capabilities
            if (verbose) {
                System.out.println("  JVM: " + vm.name() + " " + vm.version());
                System.out.println("  canRedefineClasses: " + vm.canRedefineClasses());
            }

            if (!vm.canRedefineClasses()) {
                System.err.println("JVM does not support class redefinition.");
                System.err.println("  JVM: " + vm.name() + " " + vm.version());
                System.err.println("  canRedefineClasses: " + vm.canRedefineClasses());
                System.err.println("Possible fixes:");
                System.err.println("  1. Ensure GlassFish is started with --debug=true");
                System.err.println("  2. Check domain.xml debug-options include -agentlib:jdwp=...");
                System.err.println("  3. Try adding -XX:+AllowRedefinitionToAddDeleteMethods to JVM options");
                System.exit(1);
            }

            Map<ReferenceType, byte[]> redefinitions = new HashMap<>();
            int skipped = 0;

            for (Path classFile : classFiles) {
                // Convert file path to fully qualified class name
                String relativePath = classesDir.relativize(classFile).toString();
                String className = relativePath
                        .replace(File.separatorChar, '.')
                        .replaceAll("\\.class$", "");

                // Skip inner classes generated by annotation processors (metamodel, etc.)
                // that might not be loaded yet
                List<ReferenceType> types = vm.classesByName(className);
                if (types.isEmpty()) {
                    skipped++;
                    if (verbose) System.out.println("  \u2298 " + className + " (not loaded)");
                    continue;
                }

                byte[] bytecode = Files.readAllBytes(classFile);
                if (verbose && types.size() > 1) {
                    System.out.println("  \u21BB " + className + " (" + types.size() + " types)");
                    for (int i = 0; i < types.size(); i++) {
                        System.out.println("    [" + i + "] " + typeInfo(types.get(i)));
                    }
                } else if (verbose) {
                    System.out.println("  \u21BB " + className);
                }
                for (ReferenceType type : types) {
                    redefinitions.put(type, bytecode);
                }
            }

            if (redefinitions.isEmpty()) {
                System.out.println("No loaded classes matched. " + skipped + " skipped (not loaded).");
                System.exit(0);
            }

            // Per-class redefinition: swap each class individually so one failure
            // doesn't block all others (defense against residual hierarchy issues)
            int swapped = 0;
            int failed = 0;

            for (var entry : redefinitions.entrySet()) {
                try {
                    vm.redefineClasses(Map.of(entry.getKey(), entry.getValue()));
                    swapped++;
                } catch (UnsupportedOperationException e) {
                    failed++;
                    if (verbose) System.out.println("  \u26A0 " + entry.getKey().name()
                            + " [" + classLoaderName(entry.getKey()) + "] (" + e.getMessage() + ")");
                } catch (Exception e) {
                    failed++;
                    String msg = e.getMessage() != null ? e.getMessage() : e.getClass().getName();
                    if (verbose) System.out.println("  \u2716 " + entry.getKey().name()
                            + " [" + classLoaderName(entry.getKey()) + "] (" + msg + ")");
                }
            }

            // Summary
            StringBuilder summary = new StringBuilder();
            summary.append("Hot-swapped ").append(swapped).append(" class(es).");
            if (skipped > 0) summary.append(" ").append(skipped).append(" skipped (not loaded).");
            if (failed > 0) summary.append(" ").append(failed).append(" failed (structural change).");
            System.out.println(summary);

            if (swapped == 0 && failed > 0) {
                System.err.println("No classes were swapped. Use './gf full' for structural changes.");
                System.exit(1);
            }

        } catch (Exception e) {
            String msg = e.getMessage() != null ? e.getMessage() : e.getClass().getName();
            System.err.println("Hot swap failed: " + msg);
            System.exit(1);
        } finally {
            vm.dispose();
        }
    }

    /** Returns a short diagnostic string: classloader + superclass */
    private static String typeInfo(ReferenceType type) {
        String loader = classLoaderName(type);
        String superName = "?";
        if (type instanceof ClassType ct) {
            ClassType sup = ct.superclass();
            superName = sup != null ? sup.name() : "none";
        }
        return "loader: " + loader + ", super: " + superName;
    }

    /** Returns a short classloader name for a ReferenceType */
    private static String classLoaderName(ReferenceType type) {
        try {
            var cl = type.classLoader();
            if (cl == null) return "bootstrap";
            return cl.referenceType().name();
        } catch (Exception e) {
            return "unknown";
        }
    }

    private static VirtualMachine attach(String port) throws Exception {
        AttachingConnector connector = Bootstrap.virtualMachineManager()
                .attachingConnectors()
                .stream()
                .filter(c -> c.name().equals("com.sun.jdi.SocketAttach"))
                .findFirst()
                .orElseThrow(() -> new RuntimeException("SocketAttach connector not found"));

        Map<String, Connector.Argument> arguments = connector.defaultArguments();
        arguments.get("hostname").setValue("localhost");
        arguments.get("port").setValue(port);

        try {
            return connector.attach(arguments);
        } catch (ConnectException e) {
            System.err.println("Cannot connect to debug port " + port + ". Is GlassFish running in debug mode?");
            System.err.println("Start with: ./gf start   (debug is on by default)");
            System.exit(1);
            return null; // unreachable
        }
    }
}
